### ISSUE TITLE
Files do not exist in the project

### ISSUE THREAD

**Issue by amicha24** [edwardoughton/cuba#29]
Hi, unless I did something wrong (and I will look for this to ensure) the files mentioned do not exist.

Getting Started
To begin running the code, we first need to collect the data:

**python scripts/collect_data.py**
And then process the demand inputs:

**python scripts/demand.py**
Next, we can preprocess other required data:

**python scripts/preprocess.py**
Before identifying local sites:

**python scripts/supply.py**
The energy layers also need processing:

**python scripts/energy.py**

I was looking if they are generated through a script, but I did not find anything.

Thank you for letting me know more on the issue

**Comment by edwardoughton** [comment]
Hi @amicha24, yes, the files are too large to fit in the repo, and this is still work in progress. Feel free to email me if you want to discuss collaboration, eoughton [ at ] gmu [ dot ] edu
